[package]
name = "yggdrasil-prototype"
version = "0.5.0"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>"]
edition = "2021"

[dependencies]
atspi = { path = "../atspi" }
atspi-codegen = { git = "https://github.com/yggdrasil-sr/atspi-codegen", features = ["nonblock"] }
dbus = { version = "0.9.5", features = ["futures"] }
dbus-tokio = "0.7.5"
futures = "0.3.17"
once_cell = "1.8.0"
tokio = { version = "1.13.0", features = ["full"] }
tts_subsystem = { git = "https://github.com/yggdrasil-sr/tts_subsystem" }

[features]
